services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444:4444"

  openfinancedata:
    build: .
    image: openfinancedata:latest
    container_name: openfinancedata
    environment:
      SELENIUM_MODE: "docker"
    ports:
      - "8081:8081"
