services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    shm_size: 2gb
    ports:
      - "4444:4444"

  openfinancedata:
    build: .
    container_name: openfinancedata
    ports:
      - "8081:8081"
    depends_on:
      - selenium

environment:
  - SELENIUM_MODE=docker
